/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Action } from "./components/jira-tab/jira-tab";
export namespace Components {
    interface CopyButton {
        "copyText": string;
        "text": string;
    }
    interface JiraTab {
        "actions"?: string | Action[];
        /**
          * Title of the tab, i.e. the title of the jira issue
         */
        "issueTitle": string;
        /**
          * JIRA url
         */
        "jiraBaseUrl": string;
        /**
          * jira issue key
         */
        "jiraIssueKey": string;
    }
}
declare global {
    interface HTMLCopyButtonElement extends Components.CopyButton, HTMLStencilElement {
    }
    var HTMLCopyButtonElement: {
        prototype: HTMLCopyButtonElement;
        new (): HTMLCopyButtonElement;
    };
    interface HTMLJiraTabElement extends Components.JiraTab, HTMLStencilElement {
    }
    var HTMLJiraTabElement: {
        prototype: HTMLJiraTabElement;
        new (): HTMLJiraTabElement;
    };
    interface HTMLElementTagNameMap {
        "copy-button": HTMLCopyButtonElement;
        "jira-tab": HTMLJiraTabElement;
    }
}
declare namespace LocalJSX {
    interface CopyButton {
        "copyText"?: string;
        "text"?: string;
    }
    interface JiraTab {
        "actions"?: string | Action[];
        /**
          * Title of the tab, i.e. the title of the jira issue
         */
        "issueTitle"?: string;
        /**
          * JIRA url
         */
        "jiraBaseUrl"?: string;
        /**
          * jira issue key
         */
        "jiraIssueKey"?: string;
    }
    interface IntrinsicElements {
        "copy-button": CopyButton;
        "jira-tab": JiraTab;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "copy-button": LocalJSX.CopyButton & JSXBase.HTMLAttributes<HTMLCopyButtonElement>;
            "jira-tab": LocalJSX.JiraTab & JSXBase.HTMLAttributes<HTMLJiraTabElement>;
        }
    }
}
